HealthCard/HealthCard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from health.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name="home"),
    path('login', Login,name="login"),
    path('register', Registeration,name="register"),
    path('logout', Logout,name="logout"),
    path('cancel_appointment<int:pid>', cancel_appointment,name="cancel_appointment"),
    path('patient_invoices<int:pid><str:task>', patient_invoices,name="patient_invoices"),

#Admin Url
    path('admin_dashboard', admin_dashboard,name="admin_dashboard"),
    path('admin_view_appointment', admin_view_appointment,name="admin_view_appointment"),
    path('admin_view_doctors', admin_view_doctors,name="admin_view_doctors"),
    path('admin_view_patients', admin_view_patients,name="admin_view_patients"),
    path('request_health_card', request_health_card,name="request_health_card"),
    path('grant_card<int:pid>', grant_card,name="grant_card"),
    path('card_cancelation<int:pid>', card_cancelation,name="card_cancelation"),
    path('delete_patient<int:pid>', delete_patient,name="delete_patient"),
    path('all_card_user', all_card_user,name="all_card_user"),
    path('admin_view_hospitals', admin_view_hospitals,name="admin_view_hospitals"),
    path('admin_view_medicals', admin_view_medicals,name="admin_view_medicals"),
    path('admin_hospital_appointment', admin_hospital_appointment,name="admin_hospital_appointment"),
    path('admin_patient_invoices<int:pid>', admin_patient_invoices,name="admin_patient_invoices"),
    path('admin_hospital_invoices<int:pid>', admin_hospital_invoices,name="admin_hospital_invoices"),
    path('admin_patient_search_by_id', admin_patient_search_by_id, name="admin_patient_search_by_id"),
    path('admin_profile', admin_profile, name="admin_profile"),
    path('edit_admin_profile', edit_admin_profile, name="edit_admin_profile"),

#Patient Url
    path('patient_dashboard', patient_dashboard,name="patient_dashboard"),
    path('patient_profile', Patient_Profile,name="patient_profile"),
    path('change_password', Change_Password,name="change_password"),
    path('search_doctor', search_doctor,name="search_doctor"),
    path('booking-success<int:pid>', payment_success,name="booking-success"),
    path('payment<int:pid>', payment,name="payment"),
    path('appointment<int:pid>', appointment,name="appointment"),
    path('p_appointment', p_appointment,name="p_appointment"),
    path('confirmed_p_appointment',confirmed_p_appointment,name="confirmed_p_appointment"),
    path('history_p_appointment',history_p_appointment,name="history_p_appointment"),
    path('p_search_appointment',p_search_appointment,name="p_search_appointment"),
    path('health_card',health_card,name="health_card"),
    path('thank_card',thank_card,name="thank_card"),
    path('apply_card',apply_card,name="apply_card"),
    path('search_hospital',search_hospital,name="search_hospital"),
    path('hospital_booking-success<int:pid>', hospital_payment_success,name="hospital_booking-success"),
    path('hospital_payment<int:pid>', hospital_payment,name="hospital_payment"),
    path('hospital_appointment<int:pid>', hospital_appointment,name="hospital_appointment"),
    path('cancel_hospital_appointment<int:pid>', cancel_hospital_appointment,name="cancel_hospital_appointment"),
    path('patient_hospital_invoices<int:pid>', patient_hospital_invoices,name="patient_hospital_invoices"),
    path('h_appointment', h_appointment,name="h_appointment"),
    path('confirmed_h_appointment',confirmed_h_appointment,name="confirmed_h_appointment"),
    path('history_h_appointment',history_h_appointment,name="history_h_appointment"),
    path('all_doctor_appointment',all_doctor_appointment,name="all_doctor_appointment"),
    path('all_hospital_appointment',all_hospital_appointment,name="all_hospital_appointment"),

#Doctor Url
    path('doctor_dashboard', doctor_dashboard,name="doctor_dashboard"),
    path('doctor_profile', Doctor_Profile,name="doctor_profile"),
    path('doctor_change_password', Doctor_Change_Password,name="doctor_change_password"),
    path('d_appointment', d_appointment,name="d_appointment"),
    path('update_status<int:pid>', update_status,name="update_status"),
    path('confirmed_d_appointment',confirmed_d_appointment,name="confirmed_d_appointment"),
    path('history_d_appointment',history_d_appointment,name="history_d_appointment"),
    path('add_medicine<int:pid>', add_medicine, name="add_medicine"),
    path('doctor_invoice<int:pid>', doctor_invoices, name="doctor_invoice"),
    path('doctor_cancel_appointment<int:pid>', doctor_cancel_appointment, name="doctor_cancel_appointment"),
    path('doc_patient_dashboard<int:pid>', doc_patient_dashboard, name="doc_patient_dashboard"),
    path('doctor_status<int:pid>', doctor_status, name="doctor_status"),
    path('d_search_appointment',d_search_appointment,name="d_search_appointment"),
    path('all_patient_appointment',all_patient_appointment,name="all_patient_appointment"),
    path('doctor_patient_search_by_id', doctor_patient_search_by_id, name="doctor_patient_search_by_id"),
    path('my_patient', my_patient, name="my_patient"),
    path('add_prescription<int:pid>', add_prescription, name="add_prescription"),
    path('add_presc<int:pid>', add_presc, name="add_presc"),
    path('add_medical<int:pid>', add_medical, name="add_medical"),
    path('add_bill<int:pid>', add_bill, name="add_bill"),
    path('add_bil<int:pid>', add_bil, name="add_bil"),
    path('delete_presc<int:pid>', delete_presc, name="delete_presc"),
    path('delete_bill<int:pid>', delete_bill, name="delete_bill"),

#Hospital Url
    path('hospital_dashboard', hospital_dashboard, name="hospital_dashboard"),
    path('hospital_profile', Hospital_Profile, name="hospital_profile"),
    path('hospital_change_password', Hospital_Change_Password, name="hospital_change_password"),
    path('hospital_view_appointment', hospital_view_appintment, name="hospital_view_appointment"),
    path('hospital_view_confirmed_appointment', hospital_view_confirmed_appintment,name="hospital_view_confirmed_appointment"),
    path('hospital_view_history_appointment', hospital_view_history_appintment,name="hospital_view_history_appointment"),
    path('hospital_update_status<int:pid>', hospital_update_status, name="hospital_update_status"),
    path('cancel_hospital_appointment<int:pid>', cancel_hospital_appointment, name="cancel_hospital_appointment"),
    path('hospital_search_appointment', hospital_search_appointment, name="hospital_search_appointment"),
    path('patient_search_by_id', patient_search_by_id, name="patient_search_by_id"),
    path('hospital_view_invoices', hospital_view_invoices, name="hospital_view_invoices"),
    path('hospital_status<int:pid>', hospital_status, name="hospital_status"),
    path('hospital_invoices2<int:pid>', hospital_invoices2, name="hospital_invoices2"),
    path('add_price_hospital<int:pid>', add_price_hospital, name="add_price_hospital"),

#Medical Url
    path('medical_dashboard', medical_dashboard,name="medical_dashboard"),
    path('medical_profile', Medical_Profile,name="medical_profile"),
    path('medical_change_password', Medical_Change_Password,name="medical_change_password"),
    path('medical_patient_search_by_id', medical_patient_search_by_id, name="medical_patient_search_by_id"),
    path('medical_invoices<int:pid>', medical_invoices, name="medical_invoices"),
    path('medical_add_medicine<int:pid>', medical_add_medicine, name="medical_add_medicine"),
    path('all_patient_invoices', all_patient_invoices, name="all_patient_invoices"),
    path('medical_status<int:pid>', medical_status, name="medical_status"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

HealthCard/health/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
blood_group=[('-A','-A'),
('+A','+A'),
('-B','-B'),
('+B','+B'),
('-AB','-AB'),
('+AB','+AB'),
('-O','-O'),
('+O','+O'),
]

gender=[('Male','Male'),
('Female','Female'),
('Other','Other'),
]

class Patient(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    blood_group = models.CharField(max_length=10,choices=blood_group,null=True)
    health_uid = models.CharField(max_length=16,null=True)
    ex_year= models.CharField(max_length=10,null=True)
    ex_month= models.CharField(max_length=10,null=True)
    cvv = models.CharField(max_length=10,null=True)
    mobile = models.CharField(max_length=10,null=True)
    address = models.CharField(max_length=100,null=True)
    card_status = models.CharField(max_length=100,null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.CharField(max_length=100,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, null=True)
    address = models.CharField(max_length=100, null=True)
    experience = models.CharField(max_length=100, null=True)
    specialist = models.CharField(max_length=100, null=True)
    service = models.CharField(max_length=100, null=True)
    clinic = models.CharField(max_length=100, null=True)
    cl_address = models.CharField(max_length=100, null=True)
    daystiming = models.CharField(max_length=100, null=True)
    timing = models.CharField(max_length=100, null=True)
    price = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=100,choices=gender,null=True)
    biography = models.TextField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Hospital(models.Model):
    status = models.CharField(max_length=100,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=100, null=True)
    nom_doctor = models.CharField(max_length=100, null=True)
    nom_beds = models.CharField(max_length=100, null=True)
    foundation_date = models.DateField(null=True)
    timing = models.CharField(max_length=100, null=True)
    owner_name = models.CharField(max_length=100, null=True)
    days_time = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    biography = models.TextField(null=True)
    image = models.FileField(null=True)

    def _str_(self):
        return self.user.username

class Medical(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=100,null=True)
    days_time = models.CharField(max_length=100, null=True)
    timing = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    foundation_date = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    experience = models.CharField(max_length=100, null=True)
    image = models.FileField(null=True)

    def _str_(self):
        return self.name

class Appointment(models.Model):
    doctor=models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True)
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    medical=models.ForeignKey(Medical, on_delete=models.CASCADE, null=True)
    a_date=models.DateField(null=True)
    a_timing=models.CharField(max_length=100,null=True)
    status=models.CharField(max_length=100,null=True)
    p_status=models.CharField(max_length=100,null=True)

    def _str_(self):
        return self.doctor.user.username+" "+self.patient.user.username

class Hospital_Appointment(models.Model):
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE, null=True)
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    a_date=models.DateField(null=True)
    a_timing=models.CharField(max_length=100,null=True)
    status=models.CharField(max_length=100,null=True)
    p_status=models.CharField(max_length=100,null=True)
    price=models.CharField(max_length=100,null=True)

    def str(self):
        return self.hospital.name+" "+self.patient.user.username

class Doctors_Invoice(models.Model):
    appointment = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True)
    medicine = models.CharField(max_length=100,null=True)
    prescription = models.CharField(max_length=100,null=True)
    price = models.CharField(max_length=100,null=True)

    def _str_(self):
        return self.apponitment.doctor.user.username + " " + self.apponitment.patient.user.username + " " + self.medicine


class Adminstration(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    mobile = models.CharField(max_length=10,null=True,blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    image = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.user.username

class Prescription(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100,null=True,blank=True)
    quantity = models.CharField(max_length=100,null=True,blank=True)
    days = models.CharField(max_length=100,null=True,blank=True)
    time = models.CharField(max_length=100,null=True,blank=True)
    price = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

class Medical_Record(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateField(null=True,blank=True)
    disc = models.CharField(max_length=100,null=True,blank=True)
    file = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

class Billing_Record(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=100,null=True,blank=True)
    amount = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

HealthCard/health/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password (again)',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['blood_group','mobile','address','dob','image']

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['experience','specialist','service','clinic','cl_address','daystiming','timing','gender','biography','mobile','address','dob','image','price']

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['a_date','a_timing','status','p_status']

class Hospital_AppointmentForm(forms.ModelForm):
    class Meta:
        model = Hospital_Appointment
        fields = ['a_date','a_timing','status','p_status']

class HospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['mobile','name','nom_doctor','nom_beds','foundation_date','timing','owner_name','days_time','address','image','biography']


class MedicalForm(forms.ModelForm):
    class Meta:
        model = Medical
        fields = ['mobile','name','foundation_date','timing','days_time','address','image','experience']

HealthCard/health/templates/invoices.html
<!DOCTYPE html> 
<html lang="en">
{% load static %}

<head>
		<meta charset="utf-8">
		<title>Doccure</title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0">
		
		<!-- Favicons -->
		<link href="{% static 'user/img/favicon.png' %}" rel="icon">
		
		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'user/css/bootstrap.min.css' %}">
		
		<!-- Fontawesome CSS -->
		<link rel="stylesheet" href="{% static 'user/plugins/fontawesome/css/fontawesome.min.css' %}">
		<link rel="stylesheet" href="{% static 'user/plugins/fontawesome/css/all.min.css' %}">
		
		<!-- Main CSS -->
		<link rel="stylesheet" href="{% static 'user/css/style.css' %}">
		
		<!-- HTML5 shim and Respond.js' %} IE8 support of HTML5 elements and media queries -->
		<!--[if lt IE 9]>
			<script src="{% static 'user/js/html5shiv.min.js' %}"></script>
			<script src="{% static 'user/js/respond.min.js' %}"></script>
		<![endif]-->


	<style>
	@media print{
    body * {
        visibility: hidden;
    }

    .print-container, .print-container * {
            visibility : visible;
    }
    .print-container {
        position:absolute;
        left:0px;
        top:0px;
    }
}
</style>



	</head>
	<body>
<div class="main-wrapper">
			<!-- Breadcrumb -->
			<div class="breadcrumb-bar">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-md-12 col-12">
							<nav aria-label="breadcrumb" class="page-breadcrumb">
								<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="{% url 'home' %}">Home</a></li>
									<li class="breadcrumb-item active" aria-current="page">Invoice View</li>
								</ol>
							</nav>
							<h2 class="breadcrumb-title">Invoice View</h2>
						</div>
					</div>
				</div>
			</div>
			<!-- /Breadcrumb -->
			
			<!-- Page Content -->
			<div class="content print-container">
				<div class="container-fluid">

					<div class="row">
						<div class="col-lg-8 offset-lg-2">
							<div class="invoice-content">
								<div class="invoice-item">
									<div class="row">
										<div class="col-md-6">
											<div class="invoice-logo">
												<img src="{% static 'user/img/favicon (1).png' %}" class="img-fluid" alt="Logo" style="width:130px;height:150px">
											</div>
										</div>
										<div class="col-md-6">
											<p class="invoice-details">
												<strong>Order:</strong> #00124 <br>
												<strong>Issued:</strong> {{pat.a_date}}
											</p>
										</div>
									</div>
								</div>
								
								<!-- Invoice Item -->
								<div class="invoice-item">
									<div class="row">
										<div class="col-md-6">
											<div class="invoice-info">
												<strong class="customer-text">Invoice From Clinic</strong>
												<p class="invoice-details invoice-details-two">
													Dr. {{pat.doctor.user.first_name}} {{pat.doctor.user.last_name}} <br>
													{{pat.doctor.cl_address}}<br>
													{{pat.doctor.address}}<br>
												</p>
											</div>

										</div>
										<div class="col-md-6">
											<div class="invoice-info invoice-info2">
												<strong class="customer-text">Invoice To</strong>
												<p class="invoice-details">
													{{pat.patient.user.first_name}} {{pat.patient.user.last_name}} <br>
													{{pat.patient.address}} <br>
													<br>
												</p>
											</div>
										</div>
									</div>
								</div>
								<!-- /Invoice Item -->

								<!-- /Invoice Item -->

								<!-- Invoice Item -->



								{% if task == "bill" %}
								<h2 style="font-family:roman;color:green" align="center" class="card">Doctor Bill Record</h2>

								<div class="invoice-item invoice-table-wrap">
									<div class="row">
										<div class="col-md-12">
											<div class="table-responsive">
												<table class="invoice-table table table-bordered">
													<thead>
														<tr>
															<th>Title</th>
															<th class="text-center">Amount</th>

														</tr>
													</thead>
													<tbody>
													{% for i in pat.billing_record_set.all %}
														<tr>
															<td>{{i.title}}</td>
															<td class="text-center">{{i.amount}}</td>
														</tr>
													{% endfor %}
													</tbody>
												</table>
											</div>
										</div>
										<div class="col-md-6 col-xl-4 ml-auto">
											<div class="table-responsive">
												<table class="invoice-table-two table">
													<tbody>
													<tr>
														<th>Total Amount:</th>
														<td><span>{{total}}</span></td>
													</tr>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								{% endif %}

								{% if task == "med" %}

								<h2 style="font-family:roman;color:green" align="center" class="card">Medical Record</h2>

								<div class="invoice-item invoice-table-wrap">
									<div class="row">
										<div class="col-md-12">
											<div class="table-responsive">
												<table class="invoice-table table table-bordered">
													<thead>

														<tr>
															<th>SI No.</th>
															<th class="text-center">Date</th>
															<th class="text-center">File</th>
															<th class="text-right">Description</th>
														</tr>
													</thead>
													<tbody>
													{% for i in pat.medical_record_set.all %}
														<tr>
															<td>{{forloop.counter}}</td>
															<td class="text-center">{{i.date}}</td>
															<td class="text-center">{{i.file}}</td>
															<td class="text-right">{{i.disc}}</td>
														</tr>
													{% endfor %}
													</tbody>
												</table>
											</div>
										</div>

									</div>
								</div>
								{% endif %}

								{% if task == "presc" %}

								<h2 style="font-family:roman;color:green" align="center" class="card">Doctor Prescription Detail</h2>

								<div class="invoice-item invoice-table-wrap">
									<div class="row">
										<div class="col-md-12">
											<div class="table-responsive">
												<table class="invoice-table table table-bordered">
													<thead>
														<tr>
															<th>SI NO.</th>
															<th class="text-center">Name</th>
															<th class="text-center">Quantity</th>
															<th class="text-center">Days</th>
															<th class="text-center">Time</th>
														</tr>
													</thead>
													<tbody>
													{% for i in pat.prescription_set.all %}
														<tr>
															<td>{{forloop.counter}}</td>
															<td class="text-center">{{i.name}}</td>
															<td class="text-center">{{i.quantity}}</td>
															<td class="text-center">{{i.days}}</td>
															<td class="text-right">{{i.time}}</td>
														</tr>
													{% endfor %}
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>

								{% else %}
								{% if task == "appoint" %}
								<h2 style="font-family:roman;color:green" align="center" class="card">Doctor Appointment Detail</h2>

								<div class="invoice-item invoice-table-wrap">
									<div class="row">
										<div class="col-md-12">
											<div class="table-responsive">
												<table class="invoice-table table table-bordered">
													<thead>
														<tr>
															<th>Description</th>
															<th class="text-center">Quantity</th>
															<th class="text-center">VAT</th>
															<th class="text-right">Total</th>
														</tr>
													</thead>
													<tbody>
														<tr>
															<td>General Consultation</td>
															<td class="text-center">1</td>
															<td class="text-center">$0</td>
															<td class="text-right">{{pat.doctor.price}}</td>
														</tr>
													</tbody>
												</table>
											</div>
										</div>
										<div class="col-md-6 col-xl-4 ml-auto">
											<div class="table-responsive">
												<table class="invoice-table-two table">
													<tbody>
													<tr>
														<th>Total Amount:</th>
														<td><span>{{pat.doctor.price}}</span></td>
													</tr>
													</tbody>
												</table>
											</div>
										</div>
									</div>
								</div>
								{% endif %}
								{% endif %}

								<!-- /Invoice Item -->
								
								<!-- Invoice Information -->
								<!-- /Invoice Information -->
								
							</div>
						</div>
					</div>

				</div>

			</div>
	<center><button class="btn btn-primary" onclick="window.print();">print</button></center>
</div>
    
<script src="{% static 'user/js/jquery.min.js' %}"></script>
		
		<!-- Bootstrap Core JS -->
		<script src="{% static 'user/js/popper.min.js' %}"></script>
		<script src="{% static 'user/js/bootstrap.min.js' %}"></script>
		
		<!-- Custom JS -->
		<script src="{% static 'user/js/script.js' %}"></script>
		
	</body>

<!-- doccure/invoice-view.html  30 Nov 2019 04:12:20 GMT -->
</html>

HealthCard/health/templates/login.html
{% extends 'user_navigation.html' %}
{% load static %}
{% block body %}
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">

					<div class="row">
						<div class="col-md-8 offset-md-2">

							<!-- Login Tab Content -->
							<div class="account-content">
								<div class="row align-items-center justify-content-center">
									<div class="col-md-7 col-lg-6 login-left">
										<img src="{% static 'user/img/login-banner.png' %}" class="img-fluid">
									</div>
									<div class="col-md-12 col-lg-6 login-right">
										<div class="login-header">
											<h3>Login <span>Form</span></h3>
										</div>
										{% for i in messages %}
										{% if i == "Invalid Credential" %}
												<p style="color:red">{{i}}</p>
										{% else %}
											<p style="color:green">{{i}}</p>
										{% endif %}
{% endfor %}
										<form action="" method="post">
                                            {% csrf_token %}
											<div class="form-group form-focus">
												<input type="text" class="form-control floating" name="username" required>
												<label class="focus-label">Username</label>
											</div>
											<div class="form-group form-focus">
												<input type="password" class="form-control floating" name="password" required>
												<label class="focus-label">Password</label>
											</div>

											<input type="submit" class="btn btn-primary btn-block btn-lg login-btn" value="Login">

											<div class="text-center dont-have">Don’t have an account? <a href="{% url 'register' %}">Register</a></div>
										</form>
									</div>
								</div>
							</div>
							<!-- /Login Tab Content -->

						</div>
					</div>

				</div>

			</div>
{% endblock %}

HealthCard/health/templates/register.html
{% extends 'user_navigation.html' %}
{% load static %}
{% block body %}
			<!-- Page Content -->
			<div class="content">
				<div class="container-fluid">
					<div class="row">
						{% for i in messages %}
<p style="color:red">{{i}}</p>
{% endfor %}

						<div class="col-md-8 offset-md-2">

							<!-- Account Content -->
							<div class="account-content">
								<div class="row align-items-center justify-content-center">
									<div class="col-md-7 col-lg-6 login-left">
										<img src="{% static 'user/img/login-banner.png' %}" class="img-fluid" alt="Login Banner">
									</div>
									<div class="col-md-12 col-lg-6 login-right">
										<div class="login-header">
											<h3>Registeration Form</h3>
										</div>

										<!-- Register Form -->
										<form action="" method="post">
                                            {% csrf_token %}
                                            <div class="form-check form-check-inline">
                                              <input class="form-check-input" type="radio" name="mode" id="inlineRadio1" value="Patient" required>
                                              <label class="form-check-label" for="inlineRadio1">Patient</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                              <input class="form-check-input" type="radio" name="mode" id="inlineRadio2" value="Doctor" required>
                                              <label class="form-check-label" for="inlineRadio2">Doctor</label>
                                            </div>
                                            <div class="form-check form-check-inline">
                                              <input class="form-check-input" type="radio" name="mode" id="inlineRadio3" value="Hospital" required>
                                              <label class="form-check-label" for="inlineRadio2">Hospital</label>
                                            </div>
											<div class="form-check form-check-inline">
                                              <input class="form-check-input" type="radio" name="mode" id="inlineRadio4" value="Medical" required>
                                              <label class="form-check-label" for="inlineRadio2">Medical</label>
                                            </div>
											<div class="form-group form-focus">
												<input type="text" class="form-control floating" name="username">
												<span>{{form.username.errors}}</span>
												<label class="focus-label">Username</label>
											</div>
											<div class="form-group form-focus">
												<input type="text" class="form-control floating" name="first_name">
												<span>{{form.first_name.errors}}</span>
												<label class="focus-label">First Name</label>
											</div>
                                            <div class="form-group form-focus">
												<input type="text" class="form-control floating" name="last_name">
												<span>{{form.last_name.errors}}</span>
												<label class="focus-label">Last Name</label>
											</div>

                                            <div class="form-group form-focus">
												<input type="email" class="form-control floating" name="email">
												<span>{{form.email.errors}}</span>
												<label class="focus-label">Email</label>
											</div>
											<div class="form-group form-focus">
												<input type="password" class="form-control floating" name="password1">
												<label class="focus-label">Create Password</label>
												<span>{{form.password1.errors}}</span>
											</div>
                                            <div class="form-group form-focus">
												<input type="password" class="form-control floating" name="password2">
												<span>{{form.password2.errors}}</span>
												<label class="focus-label">Confirm Password</label>
											</div>
											<div class="text-right">
												<a class="forgot-link" href="{% url 'login' %}">Already have an account?</a>
											</div>
											<button class="btn btn-primary btn-block btn-lg login-btn" type="submit">Signup</button>

										</form>
										<!-- /Register Form -->

									</div>
								</div>
							</div>
							<!-- /Account Content -->

						</div>
					</div>

				</div>

			</div>
			<!-- /Page Content -->

{% endblock %}