HealthCard/HealthCard/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from health.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home,name="home"),
    path('login', Login,name="login"),
    path('register', Registeration,name="register"),
    path('logout', Logout,name="logout"),
    path('cancel_appointment<int:pid>', cancel_appointment,name="cancel_appointment"),
    path('patient_invoices<int:pid><str:task>', patient_invoices,name="patient_invoices"),

#Admin Url
    path('admin_dashboard', admin_dashboard,name="admin_dashboard"),
    path('admin_view_appointment', admin_view_appointment,name="admin_view_appointment"),
    path('admin_view_doctors', admin_view_doctors,name="admin_view_doctors"),
    path('admin_view_patients', admin_view_patients,name="admin_view_patients"),
    path('request_health_card', request_health_card,name="request_health_card"),
    path('grant_card<int:pid>', grant_card,name="grant_card"),
    path('card_cancelation<int:pid>', card_cancelation,name="card_cancelation"),
    path('delete_patient<int:pid>', delete_patient,name="delete_patient"),
    path('all_card_user', all_card_user,name="all_card_user"),
    path('admin_view_hospitals', admin_view_hospitals,name="admin_view_hospitals"),
    path('admin_view_medicals', admin_view_medicals,name="admin_view_medicals"),
    path('admin_hospital_appointment', admin_hospital_appointment,name="admin_hospital_appointment"),
    path('admin_patient_invoices<int:pid>', admin_patient_invoices,name="admin_patient_invoices"),
    path('admin_hospital_invoices<int:pid>', admin_hospital_invoices,name="admin_hospital_invoices"),
    path('admin_patient_search_by_id', admin_patient_search_by_id, name="admin_patient_search_by_id"),
    path('admin_profile', admin_profile, name="admin_profile"),
    path('edit_admin_profile', edit_admin_profile, name="edit_admin_profile"),

#Patient Url
    path('patient_dashboard', patient_dashboard,name="patient_dashboard"),
    path('patient_profile', Patient_Profile,name="patient_profile"),
    path('change_password', Change_Password,name="change_password"),
    path('search_doctor', search_doctor,name="search_doctor"),
    path('booking-success<int:pid>', payment_success,name="booking-success"),
    path('payment<int:pid>', payment,name="payment"),
    path('appointment<int:pid>', appointment,name="appointment"),
    path('p_appointment', p_appointment,name="p_appointment"),
    path('confirmed_p_appointment',confirmed_p_appointment,name="confirmed_p_appointment"),
    path('history_p_appointment',history_p_appointment,name="history_p_appointment"),
    path('p_search_appointment',p_search_appointment,name="p_search_appointment"),
    path('health_card',health_card,name="health_card"),
    path('thank_card',thank_card,name="thank_card"),
    path('apply_card',apply_card,name="apply_card"),
    path('search_hospital',search_hospital,name="search_hospital"),
    path('hospital_booking-success<int:pid>', hospital_payment_success,name="hospital_booking-success"),
    path('hospital_payment<int:pid>', hospital_payment,name="hospital_payment"),
    path('hospital_appointment<int:pid>', hospital_appointment,name="hospital_appointment"),
    path('cancel_hospital_appointment<int:pid>', cancel_hospital_appointment,name="cancel_hospital_appointment"),
    path('patient_hospital_invoices<int:pid>', patient_hospital_invoices,name="patient_hospital_invoices"),
    path('h_appointment', h_appointment,name="h_appointment"),
    path('confirmed_h_appointment',confirmed_h_appointment,name="confirmed_h_appointment"),
    path('history_h_appointment',history_h_appointment,name="history_h_appointment"),
    path('all_doctor_appointment',all_doctor_appointment,name="all_doctor_appointment"),
    path('all_hospital_appointment',all_hospital_appointment,name="all_hospital_appointment"),

#Doctor Url
    path('doctor_dashboard', doctor_dashboard,name="doctor_dashboard"),
    path('doctor_profile', Doctor_Profile,name="doctor_profile"),
    path('doctor_change_password', Doctor_Change_Password,name="doctor_change_password"),
    path('d_appointment', d_appointment,name="d_appointment"),
    path('update_status<int:pid>', update_status,name="update_status"),
    path('confirmed_d_appointment',confirmed_d_appointment,name="confirmed_d_appointment"),
    path('history_d_appointment',history_d_appointment,name="history_d_appointment"),
    path('add_medicine<int:pid>', add_medicine, name="add_medicine"),
    path('doctor_invoice<int:pid>', doctor_invoices, name="doctor_invoice"),
    path('doctor_cancel_appointment<int:pid>', doctor_cancel_appointment, name="doctor_cancel_appointment"),
    path('doc_patient_dashboard<int:pid>', doc_patient_dashboard, name="doc_patient_dashboard"),
    path('doctor_status<int:pid>', doctor_status, name="doctor_status"),
    path('d_search_appointment',d_search_appointment,name="d_search_appointment"),
    path('all_patient_appointment',all_patient_appointment,name="all_patient_appointment"),
    path('doctor_patient_search_by_id', doctor_patient_search_by_id, name="doctor_patient_search_by_id"),
    path('my_patient', my_patient, name="my_patient"),
    path('add_prescription<int:pid>', add_prescription, name="add_prescription"),
    path('add_presc<int:pid>', add_presc, name="add_presc"),
    path('add_medical<int:pid>', add_medical, name="add_medical"),
    path('add_bill<int:pid>', add_bill, name="add_bill"),
    path('add_bil<int:pid>', add_bil, name="add_bil"),
    path('delete_presc<int:pid>', delete_presc, name="delete_presc"),
    path('delete_bill<int:pid>', delete_bill, name="delete_bill"),

#Hospital Url
    path('hospital_dashboard', hospital_dashboard, name="hospital_dashboard"),
    path('hospital_profile', Hospital_Profile, name="hospital_profile"),
    path('hospital_change_password', Hospital_Change_Password, name="hospital_change_password"),
    path('hospital_view_appointment', hospital_view_appintment, name="hospital_view_appointment"),
    path('hospital_view_confirmed_appointment', hospital_view_confirmed_appintment,name="hospital_view_confirmed_appointment"),
    path('hospital_view_history_appointment', hospital_view_history_appintment,name="hospital_view_history_appointment"),
    path('hospital_update_status<int:pid>', hospital_update_status, name="hospital_update_status"),
    path('cancel_hospital_appointment<int:pid>', cancel_hospital_appointment, name="cancel_hospital_appointment"),
    path('hospital_search_appointment', hospital_search_appointment, name="hospital_search_appointment"),
    path('patient_search_by_id', patient_search_by_id, name="patient_search_by_id"),
    path('hospital_view_invoices', hospital_view_invoices, name="hospital_view_invoices"),
    path('hospital_status<int:pid>', hospital_status, name="hospital_status"),
    path('hospital_invoices2<int:pid>', hospital_invoices2, name="hospital_invoices2"),
    path('add_price_hospital<int:pid>', add_price_hospital, name="add_price_hospital"),

#Medical Url
    path('medical_dashboard', medical_dashboard,name="medical_dashboard"),
    path('medical_profile', Medical_Profile,name="medical_profile"),
    path('medical_change_password', Medical_Change_Password,name="medical_change_password"),
    path('medical_patient_search_by_id', medical_patient_search_by_id, name="medical_patient_search_by_id"),
    path('medical_invoices<int:pid>', medical_invoices, name="medical_invoices"),
    path('medical_add_medicine<int:pid>', medical_add_medicine, name="medical_add_medicine"),
    path('all_patient_invoices', all_patient_invoices, name="all_patient_invoices"),
    path('medical_status<int:pid>', medical_status, name="medical_status"),

]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

HealthCard/health/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
blood_group=[('-A','-A'),
('+A','+A'),
('-B','-B'),
('+B','+B'),
('-AB','-AB'),
('+AB','+AB'),
('-O','-O'),
('+O','+O'),
]

gender=[('Male','Male'),
('Female','Female'),
('Other','Other'),
]

class Patient(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    blood_group = models.CharField(max_length=10,choices=blood_group,null=True)
    health_uid = models.CharField(max_length=16,null=True)
    ex_year= models.CharField(max_length=10,null=True)
    ex_month= models.CharField(max_length=10,null=True)
    cvv = models.CharField(max_length=10,null=True)
    mobile = models.CharField(max_length=10,null=True)
    address = models.CharField(max_length=100,null=True)
    card_status = models.CharField(max_length=100,null=True)
    dob = models.DateField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    status = models.CharField(max_length=100,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, null=True)
    address = models.CharField(max_length=100, null=True)
    experience = models.CharField(max_length=100, null=True)
    specialist = models.CharField(max_length=100, null=True)
    service = models.CharField(max_length=100, null=True)
    clinic = models.CharField(max_length=100, null=True)
    cl_address = models.CharField(max_length=100, null=True)
    daystiming = models.CharField(max_length=100, null=True)
    timing = models.CharField(max_length=100, null=True)
    price = models.CharField(max_length=100, null=True)
    dob = models.DateField(null=True)
    gender = models.CharField(max_length=100,choices=gender,null=True)
    biography = models.TextField(null=True)
    image = models.FileField(null=True)

    def __str__(self):
        return self.user.username

class Hospital(models.Model):
    status = models.CharField(max_length=100,null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    mobile = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=100, null=True)
    nom_doctor = models.CharField(max_length=100, null=True)
    nom_beds = models.CharField(max_length=100, null=True)
    foundation_date = models.DateField(null=True)
    timing = models.CharField(max_length=100, null=True)
    owner_name = models.CharField(max_length=100, null=True)
    days_time = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    biography = models.TextField(null=True)
    image = models.FileField(null=True)

    def _str_(self):
        return self.user.username

class Medical(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=100,null=True)
    days_time = models.CharField(max_length=100, null=True)
    timing = models.CharField(max_length=100, null=True)
    name = models.CharField(max_length=100, null=True)
    foundation_date = models.CharField(max_length=100, null=True)
    mobile = models.CharField(max_length=100, null=True)
    address = models.CharField(max_length=100, null=True)
    experience = models.CharField(max_length=100, null=True)
    image = models.FileField(null=True)

    def _str_(self):
        return self.name

class Appointment(models.Model):
    doctor=models.ForeignKey(Doctor, on_delete=models.CASCADE, null=True)
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    medical=models.ForeignKey(Medical, on_delete=models.CASCADE, null=True)
    a_date=models.DateField(null=True)
    a_timing=models.CharField(max_length=100,null=True)
    status=models.CharField(max_length=100,null=True)
    p_status=models.CharField(max_length=100,null=True)

    def _str_(self):
        return self.doctor.user.username+" "+self.patient.user.username

class Hospital_Appointment(models.Model):
    hospital=models.ForeignKey(Hospital, on_delete=models.CASCADE, null=True)
    patient=models.ForeignKey(Patient, on_delete=models.CASCADE, null=True)
    a_date=models.DateField(null=True)
    a_timing=models.CharField(max_length=100,null=True)
    status=models.CharField(max_length=100,null=True)
    p_status=models.CharField(max_length=100,null=True)
    price=models.CharField(max_length=100,null=True)

    def str(self):
        return self.hospital.name+" "+self.patient.user.username

class Doctors_Invoice(models.Model):
    appointment = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True)
    medicine = models.CharField(max_length=100,null=True)
    prescription = models.CharField(max_length=100,null=True)
    price = models.CharField(max_length=100,null=True)

    def _str_(self):
        return self.apponitment.doctor.user.username + " " + self.apponitment.patient.user.username + " " + self.medicine


class Adminstration(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    mobile = models.CharField(max_length=10,null=True,blank=True)
    address = models.CharField(max_length=100,null=True,blank=True)
    image = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.user.username

class Prescription(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    name = models.CharField(max_length=100,null=True,blank=True)
    quantity = models.CharField(max_length=100,null=True,blank=True)
    days = models.CharField(max_length=100,null=True,blank=True)
    time = models.CharField(max_length=100,null=True,blank=True)
    price = models.CharField(max_length=100,null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

class Medical_Record(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    date = models.DateField(null=True,blank=True)
    disc = models.CharField(max_length=100,null=True,blank=True)
    file = models.FileField(null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

class Billing_Record(models.Model):
    appoint = models.ForeignKey(Appointment,on_delete=models.CASCADE,null=True,blank=True)
    title = models.CharField(max_length=100,null=True,blank=True)
    amount = models.IntegerField(null=True,blank=True)

    def __str__(self):
        return self.appoint.doctor.user.username+" "+self.appoint.patient.user.username

HealthCard/health/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import *

class SignUpForm(UserCreationForm):
    password2 = forms.CharField(label='Confirm Password (again)',widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email']
        labels = {'email':'Email'}

class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ['blood_group','mobile','address','dob','image']

class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ['experience','specialist','service','clinic','cl_address','daystiming','timing','gender','biography','mobile','address','dob','image','price']

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = ['a_date','a_timing','status','p_status']

class Hospital_AppointmentForm(forms.ModelForm):
    class Meta:
        model = Hospital_Appointment
        fields = ['a_date','a_timing','status','p_status']

class HospitalForm(forms.ModelForm):
    class Meta:
        model = Hospital
        fields = ['mobile','name','nom_doctor','nom_beds','foundation_date','timing','owner_name','days_time','address','image','biography']


class MedicalForm(forms.ModelForm):
    class Meta:
        model = Medical
        fields = ['mobile','name','foundation_date','timing','days_time','address','image','experience']

HealthCard/health/templates/medical/add_medicine.html
{% extends 'medical/sidebar.html' %}
{% load static %}
{% block body %}
<h2 style="font-family:roman;color:green" align="center" class="card">All Medicines & Prescription</h2>

{% for i in messages %}
<p style="color:red">{{i}}</p>
{% endfor %}

					<div class="row">
						<div class="col-sm-12">
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<form action="" method="post">
										{% csrf_token %}
										<table class="datatable table table-hover table-center mb-0">
											<thead>
												<tr>
													<th>Medicine</th>
													<th>Time</th>
													<th>Add Price</th>

												</tr>
											</thead>

											{% for i in data.prescription_set.all %}
											<tbody>
												<tr>
													<td>
														{{i.name}}
													</td>
													<td>{{i.time}}</td>

													<td>

															<input type="text" class="form-control" value="{{i.id}}" name="id{{i.id}}" hidden>
															<input type="text" class="form-control"  name="price{{i.id}}" value="{{i.price}}">

													</td>
												</tr>
									{% endfor %}






											</tbody>

										</table>

									</div>
									<div align="center"> <input type="submit" class="btn btn-primary" value="Add"></div>
											</form>

								</div>
							</div>
						</div>
					</div>
				</div>
</div>

<script src="{% static 'admin/js/jquery-3.2.1.min.js' %}"></script>

		<!-- Bootstrap Core JS -->

		<!-- Slimscroll JS -->
        <script src="{% static 'admin/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>

		<!-- Datatables JS -->
		<script src="{% static 'admin/plugins/datatables/jquery.dataTables.min.js' %}"></script>
		<script src="{% static 'admin/plugins/datatables/datatables.min.js' %}"></script>

		<!-- Custom JS -->
		<script  src="{% static 'admin/js/script.js' %}"></script>


{% endblock %}

HealthCard/health/templates/medical/change_password.html
{% extends 'medical/sidebar.html' %}
{% load widget_tweaks %}
{% block b %}
{% load static %}

<h2 style="font-family:roman;color:green" align="center" class="card">Change Password</h2>
{% for i in messages %}
<p style="color:red">{{i}}</p>
{% endfor %}

<div class="card">
     {% for i in messages %}
                <p>{{i}}</p>
                {% endfor %}

								<div class="card-body">
									<div class="row">
										<div class="col-md-12 col-lg-6">

											<!-- Change Password Form -->
											<form action="" method="post">
                                                {% csrf_token %}
												<div class="form-group">
													<label>Old Password</label>
													<input type="password" name="pwd1" class="form-control">
												</div>
												<div class="form-group">
													<label>New Password</label>
													<input type="password" name="pwd2" class="form-control">
												</div>
												<div class="form-group">
													<label>Confirm Password</label>
													<input type="password" name="pwd3" class="form-control">
												</div>
												<div class="submit-section">
													<button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
												</div>
											</form>
											<!-- /Change Password Form -->

										</div>
									</div>
								</div>
							</div>

			<!-- /Page Content -->

{% endblock %}

HealthCard/health/templates/medical/patient_search_by_id.html
{% extends 'medical/sidebar.html' %}
{% load static %}
{% block b %}
<h2 style="font-family:roman;color:green" align="center" class="card">Patient Detail</h2>
{% for i in messages %}
<p style="color:red">{{i}}</p>
{% endfor %}

<div class="content">
				<div class="container">

					<div class="row">
						<div class="col-12">


							<!-- Schedule Widget -->
							<div class="card booking-schedule schedule-widget">

								<!-- Schedule Header -->
								<div class="schedule-header">
									<div class="row">
										<div class="col-md-12">
											{% for i in messages %}
											<p style="color:red">{{i}}</p>
											{% endfor %}
											<form action="" method="post">
												{% csrf_token %}
												<div class="form-group">

													<label>Enter Health Card Id</label>
													<input type="text" class="form-control" name="uid">
												</div>

                                                <button type="submit"  class="btn btn-primary submit-btn">Search</button>
							</form>
										</div>


										</div>
									</div>
								</div>
								<!-- /Schedule Header -->
                            </div>


							<!-- /Submit Section -->

						</div>
					</div>
				</div>
{% if data %}
<h2 style="font-family:roman;color:green" align="center" class="card">Patient Detail ({{i}})</h2>

<div class="card">
    <div class="row">
        <!-- Appointment List -->
        <div class="col-4">
            <p>
                Image
            </p>
        </div>
        <div class="col-8">
            <p>
                Patient Detail
            </p>
        </div>
    </div>
</div>

<div class="appointments">

    <!-- Appointment List -->
    <div class="appointment-list">
        <div class="profile-info-widget">
            <div class="row">
             <div class="col-4">
            <a href="#" class="booking-doc-img">
                <img src="{{data.image.url}}" alt="User Image">
            </a>
             </div>
             <div class="col-8">

                <h3><a href="#">{{data.user.first_name}} {{data.user.last_name}}</a></h3>
                <div class="patient-details">
                    <h5><i class="fas fa-map-marker-alt"></i> {{data.address}}</h5>
                    <h5><i class="fas fa-envelope"></i> {{data.user.email}}</h5>
                    <h5 class="mb-0"><i class="fas fa-phone"></i> +1 {{data.mobile}}</h5>
            </div>


    </div>
            </div></div></div></div>
<h2 style="font-family:roman;color:green" align="center" class="card">Doctors Appointment</h2>
<div class="row">
						<div class="col-md-12">

							<!-- Recent Orders -->
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="datatable table table-hover table-center mb-0">
											<thead>
												<tr>
													<th>Doctor Name</th>
													<th>Speciality</th>
													<th>Patient Name</th>
													<th>Apointment Time</th>
													<th>Status</th>
													<th>Invoice</th>
													<th>Amount Add</th>

												</tr>
											</thead>
											<tbody>
                                            {% for i in appointment %}
												<tr>
													<td>
														<h2 class="table-avatar">
															<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{i.doctor.user.doctor_set.all.0.image.url}}" alt="User Image"></a>
															<a href="#">Dr. {{i.doctor.user.first_name}} {{i.doctor.user.last_name}}</a>
														</h2>
													</td>
													<td>Dental</td>
													<td>
														<h2 class="table-avatar">
															<a href="#" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{i.patient.user.patient_set.all.0.image.url}}" alt="User Image"></a>
															<a href="#"> {{i.patient.user.first_name}}</a>
														</h2>
													</td>
													<td>{{i.a_date}} <span class="text-primary d-block">{{i.a_timing}}</span></td>
													<td> <span class="text-primary d-block">{{i.status}}</span></td>
													<td>
													  <a href="{% url 'medical_invoices' i.id %}"  class="btn btn-sm bg-info-light" >
                                                                    <i class="far fa-eye"></i> View
                                                                </a>
													</td>
													<td>
													  <a href="{% url 'medical_add_medicine' i.id %}"  class="btn btn-sm bg-info-light" >
                                                                    <i class="far fa-add"></i> + Add
                                                                </a>
													</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

{% if hos_appointment %}
<h2 style="font-family:roman;color:green" align="center" class="card">Hospitals Appointment</h2>
<div class="row">
						<div class="col-md-12">

							<!-- Recent Orders -->
							<div class="card">
								<div class="card-body">
									<div class="table-responsive">
										<table class="datatable table table-hover table-center mb-0">
											<thead>
												<tr>
													<th>Doctor Name</th>
													<th>Speciality</th>
													<th>Patient Name</th>
													<th>Apointment Time</th>
													<th>Status</th>
													<th class="text-right">Amount</th>
												</tr>
											</thead>
											<tbody>
                                            {% for i in hos_appointment %}
												<tr>
													<td>
														<h2 class="table-avatar">
															<a href="profile.html" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{i.hospital.user.hospital_set.all.0.image.url}}" alt="User Image"></a>
															<a href="profile.html"> {{i.hospital.name}} </a>
														</h2>
													</td>
													<td>Dental</td>
													<td>
														<h2 class="table-avatar">
															<a href="profile.html" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{i.patient.user.patient_set.all.0.image.url}}" alt="User Image"></a>
															<a href="profile.html"> {{i.patient.user.first_name}} {{i.patient.user.last_name}}</a>
														</h2>
													</td>
													<td>{{i.a_date}} <span class="text-primary d-block">{{i.a_timing}}</span></td>
													<td> <span class="text-primary d-block">{{i.status}}</span></td>
													<td class="text-right">

													</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
{% endif %}

{% endif %}
{% endblock %}

HealthCard/health/templates/medical/profile.html
{% extends 'medical/sidebar.html' %}
{% load widget_tweaks %}
{% block b %}
{% load static %}
<h2 style="font-family:roman;color:green" align="center" class="card">Profile </h2>

<div class="card">
				{% for i in messages %}
<p style="color:red">{{i}}</p>
{% endfor %}

</div>
<form action="" method="post" enctype="multipart/form-data">
	{% csrf_token %}
<div class="card" xmlns="http://www.w3.org/1999/html">
								<div class="card-body">
									<h4 class="card-title">Basic Information</h4>
									<div class="row form-row">
										<div class="col-md-12">
											<div class="form-group">
												<div class="change-avatar">
													{% if request.user.medical_set.all.0.image %}
													<div class="profile-img">
														<img src="{{request.user.medical_set.all.0.image.url}}" alt="User Image">
													</div>
													{% endif %}
													<div class="upload-img">
														<div class="change-photo-btn">
															<span><i class="fa fa-upload"></i> Upload Photo</span>
															<input type="file" class="upload" name="image">
														</div>
														<small class="form-text text-muted">Allowed JPG, GIF or PNG. Max size of 2MB</small>
													</div>
												</div>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Username <span class="text-danger">*</span></label>
												<input type="text" class="form-control" value="{{request.user.username}}" readonly>
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Email <span class="text-danger">*</span></label>
												<input type="email" class="form-control" name="email" value="{{request.user.email}}">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>First Name <span class="text-danger">*</span></label>
												<input type="text" class="form-control" name="first_name" value="{{request.user.first_name}}">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Last Name <span class="text-danger">*</span></label>
												<input type="text" class="form-control" name="last_name" value="{{request.user.last_name}}">
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Phone Number</label>
												{% render_field form.mobile class="form-control" %}
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group mb-0">
												<label>Date of Foundation</label>
												{% render_field form.foundation_date type="date" class="form-control" %}
											</div>
										</div>

										<div class="col-md-6">
											<div class="form-group mb-0">
												<label>Address</label>
												{% render_field form.address class="form-control" %}
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group mb-0">
												<label>Experience</label>
												{% render_field form.experience type="text" class="form-control" %}
											</div>
										</div>
									</div>
								</div>
</div>
							<!-- /Basic Information -->

							<!-- About Me -->

							<!-- /About Me -->

							<!-- Clinic Info -->
							<div class="card">
								<div class="card-body">
									<h4 class="card-title">Medical Info</h4>
									<div class="row form-row">
										<div class="col-md-6">
											<div class="form-group">
												<label>Medical Name</label>
												{% render_field form.name class="form-control" %}
											</div>
										</div>


										<div class="col-md-6">
											<div class="form-group">
												<label>Days</label>
												{% render_field form.days_time class="form-control" %}
											</div>
										</div>
										<div class="col-md-6">
											<div class="form-group">
												<label>Timing</label>
												{% render_field form.timing class="form-control" %}
											</div>
										</div>

									</div>
								</div>
							</div>

							<div class="submit-section submit-btn-bottom">
								<button type="submit" class="btn btn-primary submit-btn">Save Changes</button>
							</div>
</form>

{% endblock %}